#include <stdint.h>
#include "flags.h"
#include <capstone/capstone.h>
#include <capstone/x86.h>

#ifndef INSTR_H
#define INSTR_H

int initialize();
int aaa (cs_insn *insn);
int aad (cs_insn *insn);
int aam (cs_insn *insn);
int aas (cs_insn *insn);
int adc (cs_insn *insn);
int add (cs_insn *insn);
int and (cs_insn *insn);
int arpl (cs_insn *insn);
int bound (cs_insn *insn);
int bsf (cs_insn *insn);
int bsr (cs_insn *insn);
int bt (cs_insn *insn);
int btc (cs_insn *insn);
int btr (cs_insn *insn);
int bts (cs_insn *insn);
int call (cs_insn *insn);
int cbw (cs_insn *insn);
int cwde (cs_insn *insn);
int clc (cs_insn *insn);
int cld (cs_insn *insn);
int cli (cs_insn *insn);
int clts (cs_insn *insn);
int cmc (cs_insn *insn);
int cmp (cs_insn *insn);
int cmps (cs_insn *insn);
int cmpsb (cs_insn *insn);
int cmpsw (cs_insn *insn);
int cmpsd (cs_insn *insn);
int cwd (cs_insn *insn);
int cdq (cs_insn *insn);
int daa (cs_insn *insn);
int das (cs_insn *insn);
int dec (cs_insn *insn);
int div_i (cs_insn *insn);
int enter (cs_insn *insn);
int hlt (cs_insn *insn);
int idiv (cs_insn *insn);
int imul (cs_insn *insn);
int in (cs_insn *insn);
int inc (cs_insn *insn);
int ins (cs_insn *insn);
int insb (cs_insn *insn);
int insw (cs_insn *insn);
int insd (cs_insn *insn);
int inter (cs_insn *insn);
int into (cs_insn *insn);
int iret (cs_insn *insn);
int iretd (cs_insn *insn);
int jcc (cs_insn *insn);
int jmp (cs_insn *insn);
int lahf (cs_insn *insn);
int lar (cs_insn *insn);
int lea (cs_insn *insn);
int leave (cs_insn *insn);
int lgdt (cs_insn *insn);
int lidt (cs_insn *insn);
int lgs (cs_insn *insn);
int lss (cs_insn *insn);
int lds (cs_insn *insn);
int les (cs_insn *insn);
int lfs (cs_insn *insn);
int lmsw (cs_insn *insn);
int lock (cs_insn *insn);
int lods (cs_insn *insn);
int lodsb (cs_insn *insn);
int lodsw (cs_insn *insn);
int lodsd (cs_insn *insn);
int loop (cs_insn *insn);
int lsl (cs_insn *insn);
int ltr (cs_insn *insn);
int movs (cs_insn *insn);
int movsb (cs_insn *insn);
int movsw (cs_insn *insn);
int movsd (cs_insn *insn);
int movsx (cs_insn *insn);
int movzx (cs_insn *insn);
int mul (cs_insn *insn);
int neg (cs_insn *insn);
int nop (cs_insn *insn);
int not (cs_insn *insn);
int or (cs_insn *insn);
int out (cs_insn *insn);
int outs (cs_insn *insn);
int outsb (cs_insn *insn);
int outsw (cs_insn *insn);
int outsd (cs_insn *insn);
int pop (cs_insn *insn);
int popa (cs_insn *insn);
int popad (cs_insn *insn);
int popf (cs_insn *insn);
int popfd (cs_insn *insn);
int push (cs_insn *insn);
int pusha (cs_insn *insn);
int pushad (cs_insn *insn);
int pushf (cs_insn *insn);
int pushfd (cs_insn *insn);
int rcl (cs_insn *insn);
int rcr (cs_insn *insn);
int rol (cs_insn *insn);
int ror (cs_insn *insn);
int rep (cs_insn *insn);
int repe (cs_insn *insn);
int repz (cs_insn *insn);
int repne (cs_insn *insn);
int repnz (cs_insn *insn);
int ret (cs_insn *insn);
int sahf (cs_insn *insn);
int sal (cs_insn *insn);
int sar (cs_insn *insn);
int shl (cs_insn *insn);
int shr (cs_insn *insn);
int sbb (cs_insn *insn);
int scas (cs_insn *insn);
int scasb (cs_insn *insn);
int scasw (cs_insn *insn);
int scasd (cs_insn *insn);
int setcc (cs_insn *insn);
int sgdt (cs_insn *insn);
int sidt (cs_insn *insn);
int shld (cs_insn *insn);
int shrd (cs_insn *insn);
int smsw (cs_insn *insn);
int stc (cs_insn *insn);
int std (cs_insn *insn);
int sti (cs_insn *insn);
int stos (cs_insn *insn);
int stosb (cs_insn *insn);
int stosw (cs_insn *insn);
int stosd (cs_insn *insn);
int str (cs_insn *insn);
int sub (cs_insn *insn);
int test (cs_insn *insn);
int verr (cs_insn *insn);
int verw (cs_insn *insn);
int wait (cs_insn *insn);
int xchg (cs_insn *insn);
int xlat (cs_insn *insn);
int xlatb (cs_insn *insn);
int xor (cs_insn *insn);
int mov(cs_insn *insn);
uint32_t reg_val(int reg_id);
uint32_t eff_addr(x86_op_mem m);
uint32_t pow_i(uint32_t b, uint32_t exp);

#endif