#include <stdint.h>
#include "flags.h"

#ifndef INSTRUCTIONS_H
#define INSTRUCTIONS_H

void initialize();
int add_rm8_r8(uint8_t *mem);
int add_rm16_32_r16_32(uint8_t *mem);
int add_r8_rm8(uint8_t *mem);
int add_r16_32_rm16_32(uint8_t *mem);
int add_imm8(uint8_t *mem);
int add_imm16_32(uint8_t *mem);
int push_es(uint8_t *mem);
int pop_es(uint8_t *mem);
int opcode0F(uint8_t *mem);
int bt_r(uint8_t *mem);
int bts_r(uint8_t *mem);
int btr_r(uint8_t *mem);
int bt_imm8(uint8_t *mem);
int bts_imm8(uint8_t *mem);
int btr_imm8(uint8_t *mem);
int btc_imm8(uint8_t *mem);
int btc_r(uint8_t *mem);
int bsf(uint8_t *mem);
int bsr(uint8_t *mem);
int adc_ib_al(uint8_t *mem);
int adc_iw_id(uint8_t *mem);
int and_rm8_r8(uint8_t *mem);
int and_rm16_32_r16_32(uint8_t *mem);
int and_r8_rm8(uint8_t *mem);
int and_r16_32_rm16_32(uint8_t *mem);
int and_imm8(uint8_t *mem);
int and_imm16_32(uint8_t *mem);
int daa(uint8_t *mem);
int das(uint8_t *mem);
int aad(uint8_t *mem);
int aam(uint8_t *mem);
int aaa(uint8_t *mem);
int cmp_rm8_r8(uint8_t *mem);
int cmp_rm16_32_r16_32(uint8_t *mem);
int cmp_r8_rm8(uint8_t *mem);
int cmp_r16_32_rm16_32(uint8_t *mem);
int cmp_al_imm8(uint8_t *mem);
int cmp_eax_imm32(uint8_t *mem);
int aas(uint8_t *mem);
int inc_eax(uint8_t *mem);
int inc_ecx(uint8_t *mem);
int inc_edx(uint8_t *mem);
int inc_ebx(uint8_t *mem);
int inc_esp(uint8_t *mem);
int inc_ebp(uint8_t *mem);
int inc_esi(uint8_t *mem);
int inc_edi(uint8_t *mem);
int dec_eax(uint8_t *mem);
int dec_ecx(uint8_t *mem);
int dec_edx(uint8_t *mem);
int dec_ebx(uint8_t *mem);
int dec_esp(uint8_t *mem);
int dec_ebp(uint8_t *mem);
int dec_esi(uint8_t *mem);
int dec_edi(uint8_t *mem);
int push_eax(uint8_t *mem);
int push_ecx(uint8_t *mem);
int push_edx(uint8_t *mem);
int push_ebx(uint8_t *mem);
int push_esp(uint8_t *mem);
int push_ebp(uint8_t *mem);
int push_esi(uint8_t *mem);
int push_edi(uint8_t *mem);
int pop_eax(uint8_t *mem);
int pop_ecx(uint8_t *mem);
int pop_edx(uint8_t *mem);
int pop_ebx(uint8_t *mem);
int pop_esp(uint8_t *mem);
int pop_ebp(uint8_t *mem);
int pop_esi(uint8_t *mem);
int pop_edi(uint8_t *mem);
int arpl(uint8_t *mem);
int push_imm32(uint8_t *mem);
int opcode80(uint8_t *mem);
int add_r8_imm8(uint8_t *mem);
int adc_r8_imm8(uint8_t *mem);
int and_r8_imm8(uint8_t *mem);
int cmp_r8_imm8(uint8_t *mem);
int opcode81(uint8_t *mem);
int add_r16_32_imm16_32(uint8_t *mem);
int adc_r16_32_imm16_32(uint8_t *mem);
int and_r16_32_imm16_32(uint8_t *mem);
int cmp_r16_32_imm16_32(uint8_t *mem);
int opcode83(uint8_t *mem);
int add_r16_32_imm8(uint8_t *mem);
int adc_r16_32_imm8(uint8_t *mem);
int and_r16_32_imm8(uint8_t *mem);
int cmp_r16_32_imm8(uint8_t *mem);
int nop(uint8_t *mem);
int xchg_ecx_eax(uint8_t *mem);
int cwde(uint8_t *mem);
int cdq(uint8_t *mem);
int enter(uint8_t *mem);
int cmc(uint8_t *mem);
int opcodeF6(uint8_t *mem);
int div_al_rm8(uint8_t *mem);
int idiv_al_rm8(uint8_t *mem);
int opcodeF7(uint8_t *mem);
int div_eax_rm16_32(uint8_t *mem);
int idiv_eax_rm16_32(uint8_t *mem);
int clc(uint8_t *mem);
int cli(uint8_t *mem);
int cld(uint8_t *mem);
int dec_rm8(uint8_t *mem);
int dec_rm16_32(uint8_t *mem);
uint8_t parity(uint8_t num);
void toBin(uint8_t c, uint8_t * b);
uint8_t parse_1B_imm_op();
uint32_t parse_4B_imm_op();
void parse_ops_1B();

#endif